services:
  api:
    build:
      context: .
      dockerfile: Api.Dockerfile
    volumes:
      - ./DB:/app/DB
  ui:
    build:
      context: .
      dockerfile: UI.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
