services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  api:
    build: ./api
    volumes:
      - ./DB:/App/DB
  ui:
    build: ./ui
    env_file:
      - ./ui.env
    depends_on:
      proxy:
        condition: service_started
