services:
  rabbit-mq:
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5671:5672
      - 15671:15672
  smtp:
    image: rnwood/smtp4dev:v3
    ports:
      - 3456:80
      - 25:25
  postgres:
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql

networks:
  dev-services:
    driver: bridge

volumes:
  pgdata: