// <auto-generated />
using System;
using JDev.Tuteee.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JDev.Tuteee.Rest.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251115190758_DropDateTimeOffsets")]
    partial class DropDateTimeOffsets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.ClientRole", b =>
                {
                    b.Property<int>("ClientRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientRoleId"));

                    b.Property<int>("StakeholderId")
                        .HasColumnType("integer");

                    b.HasKey("ClientRoleId");

                    b.HasIndex("StakeholderId")
                        .IsUnique();

                    b.ToTable("ClientRole", (string)null);
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.HomeworkAttachment", b =>
                {
                    b.Property<int>("HomeworkAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HomeworkAttachmentId"));

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HomeworkAttachmentId");

                    b.HasIndex("LessonId");

                    b.ToTable("HomeworkAttachment", (string)null);
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("ClientRoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ClientRoleId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean");

                    b.Property<string>("HomeworkInstructions")
                        .HasColumnType("text");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TuteeRoleId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TuteeRoleId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RateId"));

                    b.Property<DateOnly>("DateEnabled")
                        .HasColumnType("date");

                    b.Property<int>("PencePerHour")
                        .HasColumnType("integer");

                    b.Property<int>("TuteeRoleId")
                        .HasColumnType("integer");

                    b.HasKey("RateId");

                    b.HasIndex("TuteeRoleId");

                    b.ToTable("Rate", (string)null);
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Stakeholder", b =>
                {
                    b.Property<int>("StakeholderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StakeholderId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StakeholderId");

                    b.ToTable("Stakeholder", (string)null);
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.TuteeRole", b =>
                {
                    b.Property<int>("TuteeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TuteeRoleId"));

                    b.Property<int>("ClientRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("StakeholderId")
                        .HasColumnType("integer");

                    b.HasKey("TuteeRoleId");

                    b.HasIndex("ClientRoleId");

                    b.HasIndex("StakeholderId")
                        .IsUnique();

                    b.ToTable("TuteeRole", (string)null);
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.ClientRole", b =>
                {
                    b.HasOne("JDev.Tuteee.DAL.Entities.Stakeholder", "Stakeholder")
                        .WithOne("ClientRole")
                        .HasForeignKey("JDev.Tuteee.DAL.Entities.ClientRole", "StakeholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stakeholder");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.HomeworkAttachment", b =>
                {
                    b.HasOne("JDev.Tuteee.DAL.Entities.Lesson", "Lesson")
                        .WithMany("HomeworkAttachments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Invoice", b =>
                {
                    b.HasOne("JDev.Tuteee.DAL.Entities.ClientRole", "ClientRole")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientRole");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Lesson", b =>
                {
                    b.HasOne("JDev.Tuteee.DAL.Entities.Invoice", "Invoice")
                        .WithMany("Lessons")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("JDev.Tuteee.DAL.Entities.TuteeRole", "TuteeRole")
                        .WithMany("Lessons")
                        .HasForeignKey("TuteeRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("TuteeRole");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Rate", b =>
                {
                    b.HasOne("JDev.Tuteee.DAL.Entities.TuteeRole", "TuteeRole")
                        .WithMany("Rates")
                        .HasForeignKey("TuteeRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TuteeRole");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.TuteeRole", b =>
                {
                    b.HasOne("JDev.Tuteee.DAL.Entities.ClientRole", "ClientRole")
                        .WithMany("TuteeRoles")
                        .HasForeignKey("ClientRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDev.Tuteee.DAL.Entities.Stakeholder", "Stakeholder")
                        .WithOne("TuteeRole")
                        .HasForeignKey("JDev.Tuteee.DAL.Entities.TuteeRole", "StakeholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientRole");

                    b.Navigation("Stakeholder");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.ClientRole", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("TuteeRoles");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Invoice", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Lesson", b =>
                {
                    b.Navigation("HomeworkAttachments");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.Stakeholder", b =>
                {
                    b.Navigation("ClientRole");

                    b.Navigation("TuteeRole");
                });

            modelBuilder.Entity("JDev.Tuteee.DAL.Entities.TuteeRole", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
