name: Push images to docker registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: jdev-tuteee-rest-api
            dockerfile: Rest.Api.Dockerfile
          - image: jdev-tuteee-grpc-api
            dockerfile: Grpc.Api.Dockerfile
          - image: jdev-tuteee-identity
            dockerfile: Identity.Dockerfile
          - image: jdev-tuteee-emailconsumer
            dockerfile: EmailConsumer.Dockerfile
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses:
          actions/checkout@v4
      -
        name: Read version file
        id: dotenv
        uses: falti/dotenv-action@v1.1.4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ matrix.image }}:${{ steps.dotenv.outputs.version }}