// <auto-generated />
using JDev.Tuteee.Api.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JDev.Tuteee.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250714172815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("JDev.Tuteee.Api.Entities.Guardian", b =>
                {
                    b.Property<int>("GuardianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuardianId");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("JDev.Tuteee.Api.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuteeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonId");

                    b.HasIndex("TuteeId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("JDev.Tuteee.Api.Entities.Tutee", b =>
                {
                    b.Property<int>("TuteeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuardianId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TuteeId");

                    b.HasIndex("GuardianId");

                    b.ToTable("Tutees");
                });

            modelBuilder.Entity("JDev.Tuteee.Api.Entities.Lesson", b =>
                {
                    b.HasOne("JDev.Tuteee.Api.Entities.Tutee", "Tutee")
                        .WithMany("Lessons")
                        .HasForeignKey("TuteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutee");
                });

            modelBuilder.Entity("JDev.Tuteee.Api.Entities.Tutee", b =>
                {
                    b.HasOne("JDev.Tuteee.Api.Entities.Guardian", "Guardian")
                        .WithMany("Tutees")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("JDev.Tuteee.Api.Entities.Guardian", b =>
                {
                    b.Navigation("Tutees");
                });

            modelBuilder.Entity("JDev.Tuteee.Api.Entities.Tutee", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
